[model]
package = "models.mamba"


[labels]
state_len = 5
labels = ["N", "A", "C", "G", "T"]

[input]
features = 1

# C1
[[block]]
d_model = 64
nhead = 8
d_intermediate = 0
n_layer = 1
d_state = 256
d_conv = 4
headdim = 64
expand = 2
vocab_size = 8192
pad_vocab_size = 8
chunk_size = 12000
dim_feedforward = 2048
deepnorm_alpha = 2.4494897
deepnorm_beta = 0.2886751



[basecaller]
batchsize = 128
chunksize = 12000
overlap = 600